### ISSUE TITLE
Support for webfonts

### ISSUE THREAD

**Issue by runemadsen** [jonobr1/two.js#141]
First of all, thanks for an awesome library. I'm teaching a class on algorithmic graphic design, and I'm thinking about using two.js for it. However, I would need basic webfont support to be able to teach the concepts of typography (if you're interested in the specifics, you can find [my Processing examples on this page](http://printingcode.runemadsen.com/lecture-typography/).

I wouldn't mind spending some time hacking on an implementation for this if you're interested? It could either be in the form of a PR to this repo, or some kind of external plugin file (`two.typography.js`).

My initial idea approach would be to write a webfont to `Two.Polygon` parser, but I'm not entirely sure that `Two.Polygon` can support all paths/curves from a font file?

Let me know what you think. Any help would be appreciated.

**Comment by jonobr1** [comment]
This sounds really awesome and your project page looks really interesting!

So, before we get into chatting about how to add text support to Two.js I would like say that you can import and mess with SVG's. I know it's not quite the same, but for a lot of the _glyph_ examples in your example page Two.js could do this right now. Similar to [this example](http://jonobr1.github.io/two.js/examples/animate-stroke.html). Also, [this site](http://anitype.com/entries) is all about animating glyphs programmatically and uses Two.js.

*Okay*, let's talk about text implementation. _First_, you're going to want to start working with the `dev` branch. This branch has one very crucial change. `Two.Polygon` has been changed to construct a polygon in the geometry sense (a series of vertices that compose a closed shape that are connected by straight lines). In its place there is a base drawing class called `Two.Path`. All visible objects in Two.js are built using `Two.Path` at the moment. Basically, what we would do to make text is to create a new type of object that is drawn to the renderer.

In order to do this we'll make a class, say `Two.Text` that _extends_ `Two.Shape`. `Two.Shape` is the underlying matrix for all objects in the scenegraph and is what both `Two.Group` and `Two.Path` extend. Then setup all the properties you need, like `Two.Text.prototype.lineHeight`, and follow how [`Two.Path`](https://github.com/jonobr1/two.js/blob/dev/src/path.js) is constructed for flags. Once we have this setup then we need to write the corresponding logic on each renderer found in the `/src/renderer` folder. It sounds like a lot of steps, but I'm probably missing a lot more. In addition we'll wanna write tests too, but we could get to that later.

Hopefully this gives you a high level of how you could potentially construct text within Two.js as extended like the other classes.

Finally, if this doesn't seem like an endeavor worth embarking on then I will also recommend a couple of other options:
1. You always have direct access to a renderer. e.g: `two.renderer.domElement` is the `<svg />` or `<canvas />` tag associated with your instance. Both SVG and canvas have pretty robust and well documented methods for creating text.
2. You can always use regular DOM Elements in conjunction with Two.js. e.g: `var p = document.createElement('p');` and keep these elements _on top_ of your instance of Two.js.

Hope this helps! Feel free to ask anymore questions. Also, based on the interest from the Hacker News post on text we could potentially just figure out the spec and I could add it to the next release of Two.js. :+1:

**Comment by runemadsen** [comment]
Thanks so much for this @jonobr1. This helps a ton! After comments from @mattdesl on Twitter, I realized that I'm actually looking for 2 distinct features:

1) Basic font support. This should be done by the native browser font rendering in SVG/canvas/WebGL, and can be used to create designs with typography.

2) Lower-level access to font vectors in order to manipulate them (like what I did in my lecture notes). It might be that your SVG example does the trick here, but I'll play around with it and see how it feels.

Your description of implementation steps make sense to me, and I have no problem driving this from tests. I'm not big on WebGL, but SVG and canvas should be pretty smooth. So let me think about this for a second and hope I can find time to do the actual implementation.

Thanks again for a great lib.

**Comment by mattdesl** [comment]
Here's a few of my thoughts since I've had to deal with lots of text rendering over the last several months.

I can't speak to SVG text since I haven't tried, but it seems pretty straight-forward.

Most browsers support `@font-face` with Canvas2D context, but there's no built-in word-wrapping and the support for bi-directional text is sketchy across browsers (i.e. rendering Arabic text alongside English words). You might run into issues where you cache a label to an off-screen canvas before the webfont has loaded, so you end up with some unstyled text. The [font loading](http://caniuse.com/#feat=font-loading) spec will probably resolve this once it lands in all browsers. Another major issue is a lack of font metrics: you can't reliably query the height of a text string or more specific metrics (baseline, etc).

Rendering in WebGL is a lot more difficult, and really depends on the application. Here's a few common implementations:

- Render a chunk of text to an off-screen Canvas2D using `fillText`, then **upload to a WebGL texture**. This is slow and memory intensive but it can work pretty well for static text or complex text, e.g. glyph-shaping.
- Render a chunk of text to a canvas and then **[vectorize it](https://www.npmjs.com/package/vectorize-text)**. Same limitations as above, but now you can render it in 3D and scale the label without artifacts. Not good for small fonts.
- **Process a TTF/OTF file and extract kerning & vector paths**. Good for large font sizes, dynamic labels, 3D text, low-memory devices, etc. Not good for small font sizes, not really suitable for CTL where the glyphs will need a shaping system (i.e. Latin alphabets only). If the font is rendered to an off-screen buffer (i.e. when you need post-processing) you will lose anti-aliasing, and it will look like junk.
- Render using **signed distance fields** (SDF). This is like the above but tends to look better at medium sizes (~16 - 32px), especially on retina, and gives you control over anti-aliasing. Also lots of potential for effects, shadows, etc. Some solutions go as far as doing the SDF generation server-side, so you can query any glyph dynamically from a huge font set. Downsides: not easy with CTL, not good for small/bitmap fonts, loss of typeface detail near edges, not a lot of mature JS tooling yet for this. 
- Render using **bitmap fonts**, generated offline from TTF/OTF file. This is like the above but there is no alpha-testing, so it only looks good at the exact size you generated offline. The main benefit over SDF is that it's a bit easier, looks better at small sizes, and doesn't have loss of typeface detail.

I've tried all of these and so far I'm preferring SDF for Latin languages. If CTL support is needed (i.e. Arabic) I would just avoid WebGL/Canvas entirely since it is a massive undertaking.

Anyways, a lot of work has already been done in all these areas. If `two.js` was to adopt any text stuff it would probably be a good idea to use existing modules rather than try to re-invent the wheel. :smile:

https://github.com/mattdesl/text-modules

**Comment by jonobr1** [comment]
Based on this commentary I think it's clear to take this action:

For basic text rendering we can incorporate a class like `Two.Text` or something with a bunch of properties that pull in `@font-face`. It will leverage the native `svg` and `canvas` rendering capabilities and be perfectly suited for simply setting typography. For `webgl` the text rendering will be implemented as in @mattdesl's first option via an offscreen `<canvas />` element and uploaded to `webgl` via a texture. This is actually how all the shape rendering currently works in Two.js, so it falls in line pretty nicely.

For anything outside of basic text rendering you can look elsewhere. Again, @mattdesl has compiled an awesome set of prototypes and modules that exist to do complex font and type manipulation.

I'll put this on my `todo` and make it a requirement for the *v0.5.0*.

**Comment by ColinUNCG** [comment]
@runemadsen @mattdesl @jonobr1 
Can someone give us an example?

**Comment by jonobr1** [comment]
There currently isn't a _working_ example. But I could imagine the API working something like:

````javascript
var text = new Two.Text('Hello World', x, y);

text.textAlign = 'center';
text.lineHeight = 50;
text.fontSize = 50;
text.fontFamily = 'Proxima Nova, sans-serif';
text.fill = 'rgb(255, 100, 100);

text.translation.set(two.width / 2, two.height / 2);
text.rotation = Math.PI / 3;
text.scale = 2;

two.add(text);
````

**Comment by ColinUNCG** [comment]
@jonobr1 

This is nice.  i am looking forward to the new v0.5.0.
BTW, When it will release?

**Comment by jonobr1** [comment]
ATM: Aiming for end of September.

**Comment by jonobr1** [comment]
So `v0.5.0` is out. Unfortunately, `Two.Text` didn't make it. But! It is actively in development and currently working in some form on the `dev` branch. Here's an example: https://dl.dropboxusercontent.com/u/1595444/experiments/Two.js/tests/two-text/index.html

**Comment by jonobr1** [comment]
Finished writing tests for `Two.Text`. I still need to make an example, but `Two.Text` will spearhead the release of `v0.6.0`. Keep you all posted as it develops.

**Comment by jonobr1** [comment]
Latest release is out and includes the text module. Thanks for all your help in getting this into Two.js! Here's an example use case: http://jonobr1.github.io/two.js/examples/text.html
