### ISSUE TITLE
Image as background

### ISSUE THREAD

**Issue by JDaza13** [jonobr1/two.js#183]
Hello,

I am working on a project, trying to make a rotary menu where each element works as a link to a section of the web portal. I would like to add images to each circle in order to make a better user experience. Rendering is SVG because click listeners are feaseble this way. I attached an image of the section of the project I'm working on.

![rotarymenu](https://cloud.githubusercontent.com/assets/13385606/16524185/baf7286e-3f6c-11e6-9133-6b49185964a7.png).

The icons on the right are the ones that I want to put inside the rotary menu.

Thanks.

pdta. Pardon my english.

**Comment by jonobr1** [comment]
Hey there,

Sorry for the delay! Thanks for trying out Two.js. If your images are SVG files then you can use the `load` function to load it into a Two.js scene like so:

````javascript
two.load('/path-to-svg/filename.svg', function(svg) {
  // svg is a Two.Group
});
````

Otherwise you'll have to access the SVG element directly and append an image to it... This is not very well documented, but you can access the SVG element like so:

````javascript
var path = two.makeEllipse(0, 0, 50, 50);
two.update();
var svgElem = path._renderer.elem;
````

Hope this helps!
