### ISSUE TITLE
Benchmark with particle sandbox gives very unexpected results

### ISSUE THREAD

**Issue by 0x80** [jonobr1/two.js#188]
I'm rendering 180 animated shapes with Chrome Canary using the particle sandbox from the examples [like so](http://jonobr1.github.io/two.js/examples/particle-sandbox.html?type=webgl&shapes=circle,triangle,square,pentagon,star&operations=translation,rotation,scale,vertices&count=180) from the examples.

I am using a 2015 Macbook Pro with Nvidia GPU, and I'm measuring the following framerates:

svg: 54
canvas: 47
webgl: 12

o_0 What am I missing? I was expecting something like the opposite.

**Comment by 0x80** [comment]
I found an answer on the performance of webgl in #137. It's the constant transfer of new textures that kills the performance benefit that webgl can have. So it only wins over the others if you render lots of objects without modifying their appearance.

I am still surprised that svg performs better then canvas. Under what circumstances does this occur?

**Comment by 0x80** [comment]
I found [this article](http://smus.com/canvas-vs-svg-performance/) about the performance between svg and canvas, but I still don't quite understand why svg performs better in the example.

**Comment by 0x80** [comment]
The sandbox is really nice for testing these things actually :) After playing with it some more I understand better the differences.

So I understand now that WebGL is really efficient if you just transform the shapes with rotate and translate (moving them around as static sprites), but as soon as you change the scale or shape itself the borders need to be recalculated to a texture and that is expensive.

As the SVG vs Canvas I still don't get what's going on exactly. The canvas has a lower framerate then SVG no matter what settings I try. But I do see that it also uses a lot less CPU. It looks like canvas only uses one CPU core in my computer (100%) while SVG can use more then one core (> 250%), so in that sense canvas is not necessarily less efficient then svg.

But still I don't know what the ideal conditions are for choosing canvas over svg (considering the client  supports both of course)

**Comment by jonobr1** [comment]
I'm glad you're liking the sandbox! To be totally honest, the sandboxes purpose is for this type of assessment. In the varied landscape of different devices, OS', and browsers, there is no one-size-fits-all. For each project I do a little R&D and see how they perform on various devices, OS', and browsers.

My hunch on why Canvas and SVG are performing similarly at the moment is due to the way Canvas renders it's content. Because the scene is cleared every frame the scenegraph has to repopulate all objects every frame as well. This can get cumbersome for rendering because of how many draw calls are made — especially if you have intricate or multi-nested shapes. In canvas you want to reduce your draw calls as much as possible. In SVG you want to reduce your attribute calls as much as possible.

Hope this helps!

**Comment by 0x80** [comment]
I'm not sure I understand your advise on canvas. Are you saying that the sandbox doesn't show any benefit for canvas because the code it is not written with canvas in mind? 

I clearly understand the difference in efficiency between svg and webgl when it comes to this kind of geometry, but I don't know where canvas' strength lies and why the sandbox can't demonstrate it.

**Comment by jonobr1** [comment]
Sorry, didn't mean to be obscure. Basically, for your particular computer / browser configuration there aren't apparent differences. However, that's not the case for all configurations. Mobile Safari is really good at SVG, Chrome for Android is incredibly good at canvas rendering. So these are the dimensions and variables to look at. It's not as cut-and-dry as webgl reveals. Does that make sense?

**Comment by 0x80** [comment]
Yes that makes perfect sense. Thanks for explaining!
