### ISSUE TITLE
Pooling / reusing objects? For tilesets, specifically?

### ISSUE THREAD

**Issue by Seudein** [jonobr1/two.js#212]
I tried it by making Rectangles then translating the Rectangles using a Group:

```js
loadTypes(){
	this.type = {}
	this.type.soil = new Two.Rectangle(0, 0, this.tileSize, this.tileSize)
	this.type.soil.fill = '#926239'
	this.type.water = new Two.Rectangle(0, 0, this.tileSize, this.tileSize)
	this.type.water.fill = '#a6a6ff'
}
make(type, x, y){
	var tile = this.screen.makeGroup()
	// var tileType = new Two.Rectangle(0, 0, this.tileSize, this.tileSize) //this makes it work
	// tileType.fill = type.fill
	tile.add(type)
	tile.translation.set(x*this.tileSize, y*this.tileSize)
	return tile
}
generate(width, height){
	this.tiles = []
	
	for(var x = 0; x<width; x++){
		for(var y = 0; y<height; y++){
			var ran = Math.random()
			var type = this.type.soil
			if(ran > 0.3)
				type = this.type.water
			this.tiles.push(this.make(type, x, y))
		}
	}
	this.group = this.screen.makeGroup(...this.tiles)
	this.center()
	this.group.noStroke()
}
```

but when I add a Rectangle to a new Group it seems to be removed from the old group it was assigned to.

Is there another way of doing this?

---

My intention is to use this for a tiled world map. I don't know if Two.js/SVG will auto skip drawing the elements outside of seen coordinates as well but I have a feeling no... I guess that's my next problem to tackle.

**Comment by jonobr1** [comment]
Thanks for posting! It's kind of hard to tell what you're trying to do based on pseudo code. It would be great if you had an example on jsfiddle or something like that. Then I could run and test and try to help you out.

Otherwise, if you're interested in tiling an area maybe this example on how to make a starfield in Two.js is helpful? http://codepen.io/jonobr1/full/tbAqy/

Basically, you'll have a collection of N amount of objects and their position changes as your character changes modulo the screen space.

**Comment by Seudein** [comment]
the starfield makes a set of stars then re-uses them when they get outside of the screen... I'm talking about making every possible type of object then make a grid with references to those objects. ie, make 1 star and draw it in 20 places.

Or in my case, a grass tile. Then anywhere that wants to draw this grass tile accesses one grass object to learn how to do it (so I don't make 200 grass tiles, but only 1).

here is a working example, that lags because it is making too many of the same object: http://codepen.io/anon/pen/apBOMN

^ it is generating a 100 by 100 grid, and it lags pretty bad, just about freezes my chrome.

is there any way to improve the performance? I've programmed in LIBGDX before and ran into the same problem, and the fix was to reference your tiles instead of remaking them -- GPUs like it better, keep the object in cache.

**Comment by jonobr1** [comment]
Ah, I see. Here's an example of how you would do that in Two.js. Though this doesn't really help much because this is kind of what Two.js does under-the-hood for you anyway. You won't get any real performance increase like this: https://jsfiddle.net/jonobr1/2m42pp0z/

What you can do is have your data, 100 x 100 array of objects or whatever it is. And then say maybe only 50 rectangles. Then assign positions for each rectangle based on some logic (is my object on the screen). I wanna reiterate that Two.js is _not_ a game engine. As such there's no way to tap into the GPU as your describing without just touching the underlying browser APIs yourself.

Hope this helps! I'd love to see what you make

**Comment by Seudein** [comment]
hm... I thought it used WebGL

Thanks for the help. I think I need to explore my alternatives more though =X, sorry. I did quite like your API's simplicity.

**Comment by jonobr1** [comment]
It can use WebGL but there isn't a way to instance objects the way you're
describing. Hopefully at some point in the future it will!
