### ISSUE TITLE
Add support for Node

### ISSUE THREAD

**Issue by demurgos** [jonobr1/two.js#232]
Hi,
I'd like to use your library with Node but it currently fails because `requestAnimationFrame` is missing.
I do not want to do any animations but simply render 2d images.

Specifically, I'd like to use the [`headless-gl`](https://github.com/stackgl/headless-gl) WebGL renderer, but some other renders could also be useful such as [`node-canvas`](https://github.com/Automattic/node-canvas).

Thanks.

**Comment by jonobr1** [comment]
Thanks for checking out Two.js! In order to the library in Node you currently have to use t he [`dev`](https://github.com/jonobr1/two.js/tree/dev) branch. I'm still working out kinks in this version before publishing it to stable and subsequently npm. I'm targeting end of summer to get this release out. Thanks for your patience!

Original issue here: https://github.com/jonobr1/two.js/issues/43

**Comment by demurgos** [comment]
Thanks, I've seen this issue but it was closed so it was confusing: I wasn't sure if you were still working on this. Nice to here that it's still planned.
