### ISSUE TITLE
Fastest way to draw.

### ISSUE THREAD

**Issue by trusktr** [jonobr1/two.js#237]
Here's a concept that shows drawing circles with canvas `2d`, then compositing the circles on the GPU (with Pixi.js) to animate their positions.

https://codepen.io/osublake/pen/MoMeMg

Here's a similar example using Two.js in WebGL mode:

https://jsbin.com/cexosiyegi/edit?js,output

Perhaps the first demo shows the concept of a method that Two.js can use to draw shapes more quickly.

If Two.js already does this, why is the second example much slower?

**Comment by trusktr** [comment]
In the example, it re-uses an already-draw circle at a given radius, then it tints it on the GPU to give it the desired color.

So if all the circle are any radius in between, say, 0 and 70, then there will be at most 70 canvas instances, each one with a circle draw in it. Each canvas gets re-used for all circles of the same size.

Then the circle is colored (tinted) on the GPU, which is a fast way to have many circles different color without drawing many circles to begin with.

But how would one color both fill and stroke?

Maybe a similar approach can be taken with the strokes, having strokes on separate canvases so they can be tinted separately. Maybe this can be applied to any combination of shapes.

The question is, if we don't know what the user will draw, how do we make such optimization? What happens if the user wants a gradient fill? etc.

**Comment by jonobr1** [comment]
Thanks for posting this! These are great points and Two.js does canvas -> texture2d uploads similar to Pixi.js, but more frequently with any caching mechanics in place. e.g: if you change an attribute that merits a redraw of the sprite the canvas gets uploaded again instead of caching every possible instance like pixi.

Fortunately, the time has come now that there are `Two.Texture`s and a `Two.Registry` so that we can do more of this type of caching like pixi. Someone just needs to hook it all up 😅 

This is a great issue to track the progress of it. I imagine once we have this in place it should perform "similarly" to Pixi.js.

**Comment by trusktr** [comment]
> caching every possible instance like pixi.

Actually Pixi doesn't do that either. Pixi has drawing commands, but they are functional-imperative (like Canvas 2D) rather the OOP like Two.js classes. That caching trick is specific to that Codepen, built on top of Pixi.js. But now that there's `Two.Textures` and `Two.Registry` we can probably make a similar codepen with Two.

When animating only circle positions (not radius), Two.js and Pixi perform roughly the same:

- https://jsbin.com/cocuhivomu/edit?js,output (Pixi, see it's drawing commands)
- https://jsbin.com/noyodazefo/1/edit?js,output (Two)

I suppose this is because both are saving a texture, then animating the 3000 textures with the GPU, so at that point the GPU work is almost the same. They will both slow down redrawing circles with changing radiuses.

---

A good question is: how would be perform the caching optimization of that codepen? How can we know when to do that caching?

Maybe Two can look for custom attributes on the SVG DOM that it interprets. For example, if it finds a regular SVG tree, it does what it does now. But maybe if it finds something like `will-change="cx cy r 0 50"` on a `<circle>` element (this isn't spec'd), then that can be a hint for Two to enable caching on the circles because it knows the fill/stroke/etc are constant, so it can cache up to 50 circles during load time (or similar, and re-use them all for drawing).

---

Another interesting idea I've been thinking about is just drawing everything dynamically (as current) in dev mode, then having some way to turn on an observation mode where Two (or any drawing library like Two or Pixi in general) will observe what changes happen while the mode is turned on.

While observation mode is turned on, the developer should perform every action (every transformation) that may happen to the graphics. Then the drawing library can make a record of what changes. Based on this record, it can be possible to extrapolate which optimizations can be made for production.

When the developer turns off observation mode (or some Continuous Integration service turns it off in the automatic deployment process), then an optimization spec is returned in the form of a JavaScript file that can be placed onto the page for production.

That way, for example, if we determined during observation mode that the app will be animating 1000 circles (only cx, cy, and r), then in production an optimization like in that codepen can exist specifically for the app's use-case.

This would be an alternative to the previous runtime guessing/hints technique, and could yield more precise results, but requires more work up front during development.

**Comment by jonobr1** [comment]
So sorry for the delayed response on this! I think you have some really great points. I definitely think you could modify or write something on top of the `Two.WebGLRenderer` to achieve the type of caching / observation mode system that you're describing. It would definitely take some work.., but could be well worth the exploration 👍 

One thing I want to focus on in `v0.8.0` or `v0.9.0` is to revamp `Two.WebGLRenderer`. I've been playing with more signed distance functions. I think if we can come up with a good rubric in the fragment shader to do a lot of the drawing instead of asking `canvas2d` then we wouldn't have a lot of the issues you're running into. In addition to that because Two.js is just rendering quads, we could potentially instance them to reduce the amount of draw calls and radically increase performance. At any rate, loving the discussion on this thread and very curious to know what you're using Two.js and CI systems for...

**Comment by hichem147** [comment]
I am interested in using two.js to develop something like cytoscape.js (nodes, edges, pan & zoom)
I stick to find simple tutorials. Should I go through three.js (the parent of two.js) ? Where I can find examples that can be a good starting point ? There are some concepts that are not easy to understand withoud some tutorials (like p5.js tutorials).

**Comment by jonobr1** [comment]
Hey @hichem147, thanks for checking out Two.js. Unless I'm misunderstanding your comment, this question doesn't seem relevant to this specific thread. Do you mind creating a [New Issue](https://github.com/jonobr1/two.js/issues/new) to ask your question? We can talk about solutions there. Thanks!
