### ISSUE TITLE
Problem with additional border in Two.Sprite image

### ISSUE THREAD

**Issue by sinedoOo** [jonobr1/two.js#239]
Every image added to scene as Two.Sprite have strange additional border on left. I've tested this on svg, canvas and webgl renderers. How I append image to scene?

`new Two.Sprite('image.png', 300, 300, 1 , 1, 1),`

[Screen](http://i.imgur.com/8e0xXcr.png)

**Comment by sinedoOo** [comment]
[image.png 350x439px](http://i.imgur.com/jvZTYdg.png)

`new Two.Sprite('domeny404.png', 350, 439, 1 , 1, 1)`
`new Two.Sprite('domeny404.png')`

Still the same issue - 1px border on the left side of sprite.

**Comment by jonobr1** [comment]
Thanks for sharing the image! I can reproduce this locally and it's because I use `pattern`s to generate the image. The border is the right side of the flag showing up on the wrong side because of the image size. I think I can fix this by making sure the `pattern` doesn't have a `repeat`. More soon!

**Comment by jonobr1** [comment]
Latest [`dev`](https://github.com/jonobr1/two.js/tree/dev) branch has this fixed. Thanks for reporting!
