### ISSUE TITLE
SVG Interpreter Gradient support?

### ISSUE THREAD

**Issue by ChrisBinary** [jonobr1/two.js#244]
Hi, 

Thanks for two.js, it's a great library. Is there any way for the SVG interpreter to import linearGradient objects currently? If so, can you show an example SVG?

Thanks!

Chris

**Comment by jonobr1** [comment]
Hey Chris,

Thanks for the message. Glad you like Two.js! First, you'll need to make sure you have the latest nightly which can be found [here](https://github.com/jonobr1/two.js/tree/dev/build). Then you should be able to import gradients like so: https://jsfiddle.net/jonobr1/fgtf6npx/

If you'd like to use `two.interpret` directly then it expects an SVG DOM Element as the argument. Hope this helps!

**Comment by ChrisBinary** [comment]
That works, thank you. Though it only seems to pick up gradients which immediately precede the object it is applied to in the SVG. Would it be possible to add support for gradients defined in a <defs> section defined before all the paths etc. they are applied to?

Thanks,

Chris

**Comment by jonobr1** [comment]
Sorry to hear that's the case! If you have a working SVG file I can test against that'd be really helpful!

**Comment by BradLattice** [comment]
Sorry to resurrect such an old issue and sorry for my poor english but I'm trying to use SVG's and running to many issues and I believe it's semi-related to this issue

**Im using two.intepret** and for some reason i can't get it working [here](https://jsfiddle.net/1kh8aL4t/6/) 

If I comment out `display: 'none'` it works but that's only because its html is simply putting the SVG onto the dom. For some reason this svg is displaying pure black and I'm not sure how to configure the SVG's for two.interpret to work. Any help is greatly appreciated!

**Comment by jonobr1** [comment]
Not a problem! I just updated Two.js dev branch ([link](https://github.com/jonobr1/two.js/blob/dev/build/two.js)). It should have fixes that solve some of the problems you are having with your SVG. One thing to consider is that Two.js at the moment isn't able to construe percentage values for linear gradients... Your example looks fairly similar in my local testing, but wanna give you a heads up on that.
