### ISSUE TITLE
Updating SVG <g> dimensions on window resize

### ISSUE THREAD

**Issue by jasewarner** [jonobr1/two.js#263]
I’m playing around with Two.js for the first time and trying out the linear gradient on a prototype. I’m having trouble resizing the SVG on window resize. Hopefully somebody can point me in the right direction.

The SVG sits within a `<section>` container that is set to `100vw` and `100vh`. I then create the new instance with the following code:

```
function windowSize() {
	windowW = window.innerWidth;
	windowH = window.innerHeight;
}
windowSize();

var two = new Two({
	fullscreen : false,
	type : Two.Types.svg,
	width : windowW,
	height : windowH,
	autostart: true
}).appendTo( container[0] );
```

So far, so good. However I need to update the SVG on window resize to make sure it still fills the viewport. So on resizing the window, I do the following:

```
windowSize();
two['width'] = windowW;
two['height'] = windowH;
two.renderer.setSize(windowW, windowH);
two.update();
```

This updates the SVG width and height properties, however the `<g>` within the SVG still retains the original dimensions.

Can anybody help me out with this?

**Comment by jonobr1** [comment]
Sorry you're having trouble with this! It's a bit hard to understand completely without an example, but from what I can infer there are a couple of ways to go about this:

right after you call `two.renderer.setSize(windowW, windowH);` run this:

````javascript
// I think this is the reference to the <g> tag you're referring to
two.scene.translation.set(two.width / 2, two.height / 2);
// Or wherever you'd like the "origin" to be
````

If you're taking the window `width` and `height`, then I might recommend using the `fullscreen: true` like so:

````javascript
var two = new Two({
  autostart: true,
  fullscreen: true
}).appendTo(container);

two.bind('resize', function() {
  // Update the <g> tag here and refer to two.width and two.height
});

````

This is a great question though, because now that you've brought this up it's making me rethink the `resize` function. Instead of it being an event triggered when `fullscreen: true`, this event should be triggered anytime `renderer.setSize` is invoked. This way you can use the `resize` function both on `fullscreen: true` as well as when you set it yourself. I'll add that to my roadmap. Hopefully this helps you out!~

**Comment by jonobr1** [comment]
I updated the latest `dev` branch so that you can create a `Two.Events.resize` handler for the scenario you've described. Like so:

````javascript
var two = new Two({
  width: width,
  height: height,
  autostart: true
}).appendTo(container);

two.bind('resize', function(width, height) {
  // Center scene so 0, 0 is the center of the screen
  two.scene.translation.set(width / 2, height / 2);
});

// Called from somewhere else
function setSize() {
  width = window.innerWidth;
  height = window.innerHeight;
  two.renderer.setSize(width, height);
}

````

**Comment by jasewarner** [comment]
Thanks for the help @jonobr1! Unfortunately `fullscreen: true` won’t work for this particular project as the page is made up of various sections that the user scrolls down through (Two.js gradients being in the top section which fills the viewport). Sorry I can’t post up a link to the prototype, it’s all local for the time being.

I will try out the `Two.Events.resize` handler and see how I get on.

Thanks again!
