### ISSUE TITLE
Proper way to update line endpoints?

### ISSUE THREAD

**Issue by anderspitman** [jonobr1/two.js#271]
Howdy, thanks for making such an awesome library. So far two.js has been a joy to work with.

I'm implementing a force layout graph visualization on top of two.js and [d3-force](https://github.com/d3/d3-force). On each tick of the simulation, I'm calling translation.set() for each vertex of the graph to update its position. This is working as expected. However, I don't see an obvious way to update the endpoints of the edge lines to follow the nodes. The easiest would be to create new lines, but this would be expensive. What's the proper way to update a line in two.js?

**Comment by anderspitman** [comment]
Ok so here's the first thing I tried, which seems to be working:

``` javascript
const [anchor1, anchor2] = edge.vertices;
anchor1.set(x1, y1);
anchor2.set(x2, y2);
```

Is that a proper way to do this in a performant manner?

**Comment by jonobr1** [comment]
The best way to do this is like: https://jsfiddle.net/jonobr1/edkage2g/2/

This example converts this [Block](https://bl.ocks.org/mbostock/ad70335eeef6d167bc36fd3c04378048) from d3 and renders it with Two.js instead of vanilla `<canvas />` tag. The example also uses the same technique as the original by drawing __all links__ as one line with varying commands. There are definitely some undocumented techniques in here, so I tried to comment it up to explain further to reduce draw callas and update function calls. Hope this helps!

**Comment by anderspitman** [comment]
That was quick! Thanks for the info. Pretty much makes sense. I'll give it a shot.
