### ISSUE TITLE
Is there an official support channel, or is it just the github issue tracker?

### ISSUE THREAD

**Issue by ogrotten** [jonobr1/two.js#275]
I'd like to suggest using reddit as a general support/Q&A. It's much more suited to that kind of discussion, not to mention the community aspects.

**Comment by jonobr1** [comment]
At the moment it's just the github issue tracker. There is a [`two.js` tag](https://stackoverflow.com/search?q=two.js) on Stack Overflow. But, I whole-heartedly welcome you to start a subreddit for Two.js!

I personally like the Issue Tracker because people can get a direct line of communication to me and I can prioritize and organize them based on other things going on in my life. If you do start one, I'd be happy to put it on the website somewhere.
