### ISSUE TITLE
Moving circles, image insertion problem

### ISSUE THREAD

**Issue by anb2018** [jonobr1/two.js#308]
Hi. This is the piece of my code 
`var Bubble = function () {
    function Bubble(options) {
        _classCallCheck(this, Bubble);
        this.position = options.position;
        this.velocity = options.velocity;
        this.color = options.color;
        this.shape = two.makeEllipse(0, 0, 1, 1);
        this.shape.stroke = this.color;
        var texture = new Two.Texture('https://i.imgur.com/DRmh6S9.jpg');
        this.shape.fill = texture;
        texture.scale = 0.8;
}`
Everything with the code overall works fine. Circles moving around and coliding with each other, but any attempt to insert an image fails. Two.Texture isn't working. The circles just get filled with one color (grey or black depending on my texture.scale value.). The image doesn't really get inserted. What do I do?

**Comment by jonobr1** [comment]
Thanks for your question @anb2018. There are potentially many reasons why this isn't working... First, can you let me know which version of the library you're using? Second, are you using the `WebGLRenderer`?

I ask because [this demo](https://jsfiddle.net/jonobr1/ksevfm92/) works for me using a similar construction. It doesn't however work in the `WebGLRenderer`, which I can fix.

If it's none of the above have you tried making the ellipse bigger? a 1px by 1px ellipse is almost impossible to see on a normally constructed Two.js stage.

**Comment by anb2018** [comment]
https://codepen.io/abhishek_nemkumar/pen/mGJMaL?editors=0010
This is the code. The problem that I faced was that when the bubbles were moving, the image insertion did not work, but when the shape is stationary then image insertion works. I am trying to make a dashboard where I can insert user images into each moving/colliding ellipse. I tried using texture but it didn't work on the moving circles.
Take a look at lines 39-41 that have been commented out. Please can you help me out? Also, thank you very much for your quick response

**Comment by jonobr1** [comment]
Your demo should use this version: `https://cdnjs.cloudflare.com/ajax/libs/two.js/0.7.0-alpha.1/two.js`

**Comment by anb2018** [comment]
Yes. Thank you once again for your really quick reply.  The problem still persists in a different way.

Now instead of the image that should be inserted, there is a color that appears. 
When I attempt the same thing on a stationary object, it works.

https://codepen.io/abhishek_nemkumar/pen/mGJMaL?editors=1010

What I was trying to ask you about earlier was that when the object is stationary, image insertion is successful, but for moving objects it fails. In the code pen above, I have put a stationary circle and 3 circles in motion/collision  and only the case where the object is stationary the image appears. 
Any idea why this might happen?
Also, thank you so very much for all your quick replies.

**Comment by jonobr1** [comment]
I don't know exactly what's going on in your code.., but if you _don't_ change the `scale` and instead chance the `width` / `height` properties on the ellipse in around line 51 it should work more consistently. e.g:

```javascript
createClass(Bubble, [{
					key: 'updateShape',
					value: function updateShape(scale) {
							this.shape.translation.copy(this.position);
                                                          this.shape.width = scale;
                                                          this.shape.height = scale;
					}
			}
```

I think it's because the image is so big it's showing such a small portion of it that it looks likes a color. If you change the `width` and `height` properties instead then you'll be keeping the image in a better range. Hope this helps!

**Comment by anb2018** [comment]
Thank you soooo much! This works. Wow. Thank you.

**Comment by jonobr1** [comment]
Happy coding! 🎊
