### ISSUE TITLE
Error drawing dashes on dev version

### ISSUE THREAD

**Issue by lucabecchetti** [jonobr1/two.js#357]
Hi guys, thanks for a great Job! I found a visible rendering bug on a dev version using dashes, i have dashes like these:

`[20, 15, 4, 15]`

In a line, it works fine!
![Schermata 2019-03-29 alle 16 43 47](https://user-images.githubusercontent.com/16253548/55244804-2dba1600-5242-11e9-8944-9c659fec81e8.png)

in a circle, works fine too, but on the arc, it drew wrong and different, based on arch width!

![Schermata 2019-03-29 alle 16 44 42](https://user-images.githubusercontent.com/16253548/55244891-57733d00-5242-11e9-82ff-a77b162860df.png)

Any suggestion?

**Comment by jonobr1** [comment]
Thanks for posting. Are you using the `Two.ArcSegment` / `two.makeArcSegment` with the shapes shown above?

**Comment by lucabecchetti** [comment]
@jonobr1 here the code:

`const screw = two.makeGroup();
        const or = diameter / 2;
        const arc = two.makeArcSegment(
            ox, oy,
            or, or,
            sa, ea,
        );
        arc.dashes = Rows.getDashesForStyle(style);
        screw.add(arc);`

**Comment by jonobr1** [comment]
I'm not totally sure on this, but it looks like because there is no difference between `innerRadius` and `outerRadius` on your `Two.ArcSegment`s. What Two.js is doing behind the scenes is rendering a path along the arc _twice_ which results on the stroke _looking_ like the behavior is different. I've been testing that here: https://jsfiddle.net/jonobr1/pmL4buj8/

I think a solution for you would be to construct a `Two.Circle` and then change the `beginning` and `ending` properties to create the arc that you want. The example posted above has an arc on the right side of the screen that is doing that. Hope this helps!

**Comment by lucabecchetti** [comment]
@jonobr1 using a circle dashes are correct, but how can I draw the same arc of a picture, using an arc?

**Comment by jonobr1** [comment]
In the example above you can match your `startAngle` and `endAngle` from `Two.ArcSegment` to `beginning` and `ending` properties respectively on the new `Two.Circle` That should create a similar arc. If there are "two" visible arcs then you can make two circles.

Alternatively you can create your own `Two.Path` and have finer grain control of the vertices and copy some of the logic from the `_update` method in `Two.ArcSegment`.
