### ISSUE TITLE
Feasible? Two.js in canvasA, Three.js in canvasB, wrapped in Electron.

### ISSUE THREAD

**Issue by rKinson** [jonobr1/two.js#358]
I'm from a Java background moving into HTML5 development because the project I want to develop next using JavaFX requires 3D views using OpenGL but... that can't happen using JavaFX. 

I'm at the planning stage of a war game that needs both 2D views of interactive maps and 3D interactive views of battles, wrapped within a UI that can run on Windows, MacOS and Linux. HTML5 technology is new to me so I just wanted to check the feasibility of the following:
- Using Electron to provide desktop cross-platform distribution.
- Something like Angular for UI.
- Two.js for the interactive 2D mapping.
    - Within separate canvas elements.
- Three.js for the interactive 3D battles - not FPS, more like moving around in the view.
    - Within separate canvas elements.

Are any WebGL conflicts inherent in the above?

Additionally, can events be exchanged between Two.js, Three.js and Angular?

Thanks for reading.

**Comment by jonobr1** [comment]
In theory this sounds like it would work. I've never personally tried though. If these views are discrete and separate areas of the user's screen then your structure sounds good. But, if you're overlaying all the content: UI, 2D, 3D on top of each other it makes more sense to render everything in one canvas. This is due to the way the browser (electron included) handles repaints and draw calls. It will be much faster to have one canvas element then trying to superimpose many different types of elements that change with transparency. Hope this helps!

**Comment by rKinson** [comment]
@jonobr1 Very helpful. Thank you for taking the time to respond.

**Comment by jonobr1** [comment]
Glad it helps!
