### ISSUE TITLE
Is this effect achievable with TwoJS? 

### ISSUE THREAD

**Issue by BradLattice** [jonobr1/two.js#376]
https://codepen.io/Spectral/pen/KareXj

I'm trying to find a way to deform a shape to give it the skewing effect and tilting effect in TwoJS? I've looked through the documentation on the site and a bit of the source code and can't seem to find anything. 

If there is a better place to ask questions for TwoJS please let me know. 

Thanks again for working so hard!

**Comment by jonobr1** [comment]
You can construct a custom matrix calculation for a Two.Path like so ([link](https://jsfiddle.net/jonobr1/bk3rhpuy/)).

Though I don't think the `skewX` and `skewY` features will give you the same effect your looking for from the jQuery Tilt library. You may have to go into that library and see exactly what the exact element transformations are in order to achieve the effect to mimic it in Two.js. Hope this helps!

**Comment by BradLattice** [comment]
Sorry for the late reply!

It definitely is matrix calculations, Thanks for the fiddle, I finally got the effect desired!

**Comment by jonobr1** [comment]
Glad to hear!
