### ISSUE TITLE
Two.Rectangle isn't fully drawn when .ending = 1

### ISSUE THREAD

**Issue by eulertour** [jonobr1/two.js#383]
The issue is exemplified here:
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="./node_modules/two.js/build/two.js"></script>
  </head>
  <body>
    <div id="two"/>
    <script>
        let elem = document.getElementById('two');
        let two = new Two({
          width: 600,
          height: 300
        }).appendTo(elem);

        let rect = two.makeRectangle(60, 60, 50, 50);
        rect.linewidth = 10; 
        rect.stroke = "#ff0000";
        rect.noFill();
        rect.ending = 0;
        rect.closed = 0;

        two.bind('update', function() {
            rect.ending += 0.005;
        }).play();
    </script>
  </body>
</html>
```
If this is intended for a non-closed rectangle, is there a different way to animate all 4 sides being drawn?

**Comment by jonobr1** [comment]
Yeah, I'd need to dig up the issue posted some months ago, but this is due to someone else being upset that a rectangle had 5 vertices.

You'll see in the source code of Two.Rectangle that there is a commented out 5th very that would make the beginning / ending animation smooth.

For the time being you can make a Two.Path with 5 points, that way you can smoothly animate. I know it sounds lame, but it's going to take some time to figure out a more robust solution.

**Comment by jonobr1** [comment]
This is fixed with this issue: https://github.com/jonobr1/two.js/issues/530
