### ISSUE TITLE
Superscript and subscript capability on Two.text

### ISSUE THREAD

**Issue by gdorfsmanhopkins** [jonobr1/two.js#401]
So sorry if this has already been addressed, but can we use superscripts and/or subscripts on two.text?  I can't seem to find this.

**Comment by jonobr1** [comment]
There's not a specific way, but off the top of my head here are two ways you could go about creating the same effect: https://jsfiddle.net/jonobr1/uj8ch1qb/4/

1. Certain typefaces incorporate superscript / subscript unicode characters. In that case you can just add them in the `message` argument of `Two.Text`.
2. You can also create separate `Two.Text` elements and compose them on a page to resemble superscript or subscript. This could be beneficial because you can animate the two elements independently.

Hope this helps!
