### ISSUE TITLE
Matrix isn't cloned for some shapes with Two.Path.clone

### ISSUE THREAD

**Issue by eulertour** [jonobr1/two.js#405]
The logic for copying Path.matrix isn't present in the clone methods for shapes subclassing Two.Path such as Two.Circle. For that reason, the script from #402 still shows a problem.

**Comment by eulertour** [comment]
Also, the solution implemented in 001d15d51776f1f441ac3ed238e4d574fc233325 uses [`Two.Matrix.copy`](https://github.com/jonobr1/two.js/blob/dev/build/two.js#L4532), which doesn't copy the `manual` property. Did you mean to use [`Two.Matrix.clone`](https://github.com/jonobr1/two.js/blob/dev/build/two.js#L4929), and if not what do you think of calling `Two.Matrix.copy` within `Two.Matrix.clone` to prevent duplicating the code?

**Comment by jonobr1** [comment]
Thanks for your diligence and sorry again about this mishap. I've been traveling so it's been difficult to properly focus on the task at hand. I've made `Two.Matrix.clone` call `Two.Matrix.copy` to reduce duplicates and I've also included the copying logic within the `clone` methods of all shapes. This is all reflected in the latest dev branch.

**Comment by eulertour** [comment]
There's also a lot of duplicated code between the different `clone` methods [[1](https://github.com/jonobr1/two.js/blob/dev/build/two.js#L10269)][[2](https://github.com/jonobr1/two.js/blob/dev/build/two.js#L9247)][[3](https://github.com/jonobr1/two.js/blob/dev/build/two.js#L10688)][[4](https://github.com/jonobr1/two.js/blob/dev/build/two.js#L15407)]. I'm not entirely sure how much of this is intentional (is there a reason only `Path.clone` and `Group.clone` call `clone._update()`, or why only only `Group.clone` copies `this.mask`?) but it'd be cleaner for both the current classes and later classes that extend them if the common lines were factored into a helper function.

By the way I'm very impressed both with two.js and how proactive you've been with responding to issues, so thank you!

**Comment by jonobr1** [comment]
Glad you like it and happy to help out. I think that's a great point to properly extend the cloning methods so that it's A) clear and B) less prone to human errors.

To answer your specific question, only `Path.clone` and `Group.clone` call the `_update` function in their respective methods because all the inherited shapes call `_update` on construction.

Though I think to start a discussion around your main question everything except the `vertices`, `curved`, `closed`, and `manual` can be inherited by the other clone methods. In this way the new clone method for everything that extends a `Two.Path` could be:

````javascript
Two.Circle.prototype.clone = function(parent) {
  var clone = new Two.Circle(0, 0, this.radius, this.vertices.length);
  if (parent) {
    parent.add(clone);
  }
  return clone.copy(this);
};
````

Where `copy` would handle all the duplicated logic in the clone method like `translation`, `rotation`, `scale`, `matrix`, etc..

**Comment by jonobr1** [comment]
This is copied in higher order shapes now
