### ISSUE TITLE
Dark fringe around WebGL object edges

### ISSUE THREAD

**Issue by adroitwhiz** [jonobr1/two.js#409]
Currently, there's a black outline/fringe around objects in the WebGL renderer:

![image](https://user-images.githubusercontent.com/25993062/69973404-73c22a80-14f1-11ea-9fff-cd4b57b6eb95.png)

This seems to be because `UNPACK_PREMULTIPLY_ALPHA_WEBGL` is disabled, and hence texture sampling occurs before alpha multiplication, leading to [incorrect results](http://www.realtimerendering.com/blog/gpus-prefer-premultiplication/).

[It seems like the code is there, but is disabled, linking to a cryptic Chrome bug I don't have permission to access.](https://github.com/jonobr1/two.js/blob/0a1624eb417bb047849d7eb2061fc4816919f424/src/renderer/webgl.js#L1312)

[Furthermore, it was added in a seemingly unrelated commit.](https://github.com/jonobr1/two.js/commit/027ecba5dcaaf4213779ff2f4f4bc5508bf38611)

**Comment by jonobr1** [comment]
Thanks for posting this issue. Unfortunately, it's a bit more complicated than this due to the way the masking works in the WebGL Renderer. I'll have a closer look at this tomorrow and try to come up with a good solution. If you need something work immediately you can switch the blend functions to:

````javascript
gl.blendEquation(gl.FUNC_ADD);
gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
````

Instead of what's there now, the `blendEquationSeparate` for some reason has the artifacts. If you know a lot about stencil functions and operations I'd love to chat with you. Someone with expertise in this area -- I think -- would be able to solve this issue pretty quickly.
