### ISSUE TITLE
Empty paths with translated matrices break getBoundingClientRect()

### ISSUE THREAD

**Issue by eulertour** [jonobr1/two.js#429]
This script exemplifies the problem:
```
<!doctype html>
<html>
  <head>
    <script src="./two.js/build/two.js"></script>
  </head>
  <body>
    <script>
        let two = new Two({ width: 600, height: 300 }).appendTo(document.body);
        let p = new Two.Path();
        p.matrix.manual = true;
        p.matrix.identity().translate(8000, 0);
        let c = new Two.Circle(0, 0, 50);
        let g = two.makeGroup(p, c);
        console.log(g.getBoundingClientRect());
        /*
        {
          bottom: 50.5,
          height: 101,
          left: -50.50000000000001,
          right: 8000,
          top: -50.50000000000001,
          width: 8050.5,
        }
        */
        two.update();
    </script>
  </body>
</html>
```
The rectangle should have `.right = 50.5` and `.width = 101`.

**Comment by jonobr1** [comment]
Thanks for posting. I think this is up for debate. I think it makes sense for the object to be the values commented out because while there aren't rendered "visible" pixels for the path with no vertices, the path is in the group's graph. This will be handy when `Two.Path`s can have children of their own.

I'd like to hear more of why you think it should be something else.

**Comment by eulertour** [comment]
I'm not sure I understand your justification; why is it useful for the bounding rect to reflect the translation of empty Paths even if they can have children of their own? I would expect them to behave the same that Groups do currently, where the parent matrix is used to compute the location of child pixels. The way it is now, there's no consistent way to get the bounding rect of a Group that contains empty Paths.

**Comment by jonobr1** [comment]
I guess my main concern is that you could have a number of empty paths and not even realize it because it doesn't get rendered nor does it return any of its matrices. I made a fix to handle your edge case, but looking at Illustrator further: if you remove all the vertices of a path it automatically removes the path. This brings me to a larger, more existential question, what's the benefit of having paths with empty vertices?

This commit patches Two.js to work as you've asked: https://github.com/jonobr1/two.js/commit/e4f24456957febea4d9dd57394b3a197710ee013

**Comment by eulertour** [comment]
Thanks for making this change.
I'd consider it to be more a problem with the developer's code if it allows for a way that empty paths can be added without their knowledge. Personally I was using empty paths in two cases: for a custom Group class which could have its own points as well as child paths, and to represent children that had been instantiated but not yet populated with data. I realize that each of these could be done with a throwaway value such as null, but I'd never considered it to be an unusual way to use paths.

**Comment by jonobr1** [comment]
For sure, the library should allow advanced developers like yourself an expressive-ness to develop projects in your own style. However, I do worry that beginners may need more guidance and that it could be a point where they get tripped up. Anyway, something to think about. Thanks again for your feedback!
