### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by jonobr1** [jonobr1/two.js#459]
<img width="1552" alt="Screen Shot 2020-04-21 at 3 56 44 PM" src="https://user-images.githubusercontent.com/220033/79908152-bcb74480-83e8-11ea-80a8-c2bdedede7f9.png">

@adroitwhiz, looks like one of the dependencies you added requires this package that has a vulnerability. Any thoughts on what this could be / how to fix it?

**Comment by adroitwhiz** [comment]
![image](https://user-images.githubusercontent.com/25993062/79908774-d3aa6680-83e9-11ea-872e-50bf2fc138a6.png)

It looks like this is coming from a dev dependency. I've encountered this before and find it quite annoying that GitHub sends you these scary security alerts because there's a vulnerability in the argument parser used by one of your build tools.

**Comment by jonobr1** [comment]
Ahhhh, got it. Thanks for the quick response. That totally makes sense.
