### ISSUE TITLE
[Bug] Objects created by Two.makeX can't be removed

### ISSUE THREAD

**Issue by boldenburg** [jonobr1/two.js#520]
**Describe the bug**
Calling Two.remove on an object that has been created and added by Two.makeX does not remove the object, even when that object is later fetched by Two.scene.getById.

**To Reproduce**
https://jsfiddle.net/2n4j0to9/ -- Click on bottom right demo area to trigger object removal.

**Expected behavior**
Calling Two.remove on an object that has been created and added by Two.makeX removes the object, both when calling Two.remove on the object and when the object is fetched by Two.scene.getById.

**Environment (please select one):**
- [x] Code executes in browser (e.g: using script tag to load library) -- tested with module and non-module library versions
- [ ] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89

**Comment by jonobr1** [comment]
Thank you for this! I've updated the dev branch to reflect [changes](https://github.com/jonobr1/two.js/commit/7118528cec6c4f156c5ae9a17127a8b44ef8a16a) / fixes to this issue. The problem is that when you change an `id` of a child element after it's been added to a group, the group's internal map doesn't update as well. It now does.
