### ISSUE TITLE
Is it okay to create multiple two instances?

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#522]
**Describe your question**
Just asking from the performance point of view.

I have a use-case where I need to create multiple `two` instances and I wanted to ask that 
- will it affect performance? 
- Is it considered okay or it's a bad practice?

**Comment by jonobr1** [comment]
Depends on a number of factors:

+ Are they all updating at the same time or one at a time?
+ Are you removing the instance from the DOM if you stop using it?

I have a sense you already know the answer before asking me because you're asking if it's bad practice, not "what's the right way to have 10 instances on the page".

So, the short answer is there is no rule. You can certainly have more than one instance of Two on one page.

If you do, the more instances you have on the page and update each animation frame the performance will decrease. But, this is pretty much the same guidance as anything in web development. I will say, it's likely that you can have more `<img />` tags on the page than instances of Two.js because an image is a native dom element that doesn't have a bunch of other JavaScript attached to it that is allocated to memory. It also doesn't update every frame like Two.js (which is every frame if you're animating).

One caveat I will add is that if you do have multiple instances and you want to deallocate all references to it, you'll need to remove it from the list of `Two.Instances`. This array has a reference to every made Two.js instance so you can easily access them all globally.

**Comment by meetzaveri** [comment]
Got it. Thanks for clarification on this topic. Closing this now!
