### ISSUE TITLE
How do I create a Bezier Curve

### ISSUE THREAD

**Issue by ivanbacher** [jonobr1/two.js#528]
**Describe your question**

I have four points: `(x1, y1), (x2, y2), (x3, y3), (x4, y4)`

I would like to create a curve from x1,y1 to x4,y4.

Not using two.js I would do it like this: 

```
let pathString =  `M${x1},${y1}C${x2},${y2},${x3},${y3},${x4},${y4}`
```

In two.js I tried this:

```
let points = [
      new Two.Anchor(x1, y1, 0, 0, 0, 0, Two.Commands.move),
      new Two.Anchor(x2, y2, 0, 0, 0, 0, Two.Commands.curve),
      new Two.Anchor(x3, y3, 0, 0, 0, 0, Two.Commands.curve),
      new Two.Anchor(x4, y4, 0, 0, 0, 0, Two.Commands.curve)
    ];
    
let bezierPath = new Two.Path(points);
bezierPath.automatic = false;
bezierPath.fill = 'none';

mainGroup.add(bezierPath);
```

Doesn't seem to be working though. This is what I get:

![Screenshot 2021-04-20 at 16 27 40](https://user-images.githubusercontent.com/5493114/115413335-5f212800-a1f5-11eb-9790-2a00e6b98ee2.png)

Any advice?

**Comment by ivanbacher** [comment]
```
points[0].relative = true;
points[1].relative = false;
points[2].relative = false;
points[3].relative = true;

![Screenshot 2021-04-21 at 10 12 09](https://user-images.githubusercontent.com/5493114/115520127-1e272300-a28a-11eb-9e73-994c8fb79723.png)

**Comment by ivanbacher** [comment]
I think I finally got it. 

```
let points = [
      new Two.Anchor(x1, y1, null, null, x2, y2, Two.Commands.move),
      new Two.Anchor(x4, y4, x3, y3, null, null, Two.Commands.curve)
    ];
    
points.forEach(p => p.relative = false);
```

![Screenshot 2021-04-21 at 11 17 01](https://user-images.githubusercontent.com/5493114/115529333-1ae46500-a293-11eb-99c1-3252b83a75de.png)

**Comment by jonobr1** [comment]
Nice work! Sorry for the delayed response and for the confusion here. Hopefully what you've learned (and I'm inferring this from your tests). The four arguments after the `x1`, `y1` represent the position of where the bezier control points lie. So, `x2`, `y2` are the `anchor.controls.left` position and `x3`, `y3` are the `anchor.controls.right` position. By default these are relative to `x1`, `y1` meaning that if you put `0` for all values you would get no curve because the control points would be at `x1`, `y1`. By setting `anchor.relative = false` you are disregarding that orientation and using the orientation of the path's matrix. Meaning that `0`, `0` would be at the path's origin, not the anchor's.

Nice work!

**Comment by ivanbacher** [comment]
Awesome! Thanks for replying.
