### ISSUE TITLE
How to update vertices of an arrow ?

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#569]
When I update vertices using `line.vertices[1].y = 200` it updates y2 but the arrow head is seen broken. Here I have attached two images. 
1st Image contains idle position 
2nd Image contains where I have updated y2 by doing `line.vertices[1].y = 200`
![chrome-capture (21)](https://user-images.githubusercontent.com/21293048/143727207-cd5bdb94-b4f7-4b69-8e14-61f7e9c1342c.jpg)
![chrome-capture (22)](https://user-images.githubusercontent.com/21293048/143727220-c1c01892-caf1-4b07-ac45-0b6cb8abf40b.jpg)

Can you guide whats the correct approach to update vertices without breaking arrow head? 
Thanks!

**Comment by jonobr1** [comment]
Unfortunately you cannot update `line.vertices[1].y` and expect the arrow to automatically update. The `two.makeArrow` doesn't make an actual arrow primitive, it just makes the vertices needed to render an arrow out of a `Two.Path`.

So, you'll have to change more than just `vertices[1]` in order to make the arrow consistent. I would like to add a `Two.Arrow` primitive to the library at some point in the future though.

**Comment by meetzaveri** [comment]
@jonobr1 Good to know. 

I already did some hack by taking a little help from `makeArrow` definition from lib source code. I created custom vertices(just as it was written in source code) and passed it to `line.vertices`. And it works!

**Comment by jonobr1** [comment]
Awesome, glad to hear!
