### ISSUE TITLE
Website examples

### ISSUE THREAD

**Issue by xixixao** [jonobr1/two.js#58]
First time I saw the website I didn't even realize the sources were editable. Even on my retina pro, I can't see the sources and their canvases at the same time. Consider putting them side by side or at least after each other.

**Comment by rupl** [comment]
An easy way to fix this might even be to leave a note saying the examples are _above_, or shuffling these blocks so the rendered example is below the code. I totally missed how I was altering the "Drawing Your First Shape" example because I was looking at the two.js instance directly below the code block.

I've significantly decreased my browser text size to produce this screenshot, but using the default size the problem was even more exaggerated since the code block and the second canvas were almost perfectly grouped together on my screen.

<img width="392" alt="twojs-demo-code-blocks" src="https://cloud.githubusercontent.com/assets/254753/12701776/5c832952-c84f-11e5-949b-99590b1b5126.png">

**Comment by jonobr1** [comment]
Good call. I'll swap them so though output is below the code. Thanks!

**Comment by jonobr1** [comment]
https://github.com/jonobr1/two.js/commit/e4951eb0a665f1a7c724fbfd6683aa0bc14a86c2

**Comment by rupl** [comment]
nice, thank you on behalf of all first-time visitors!
